name: bloc_dependency_manager
description: A package that helps manage bloc dependencies.

version: 1.0.1
homepage: https://github.com/hamed-rezaee

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.4
  equatable: ^2.0.5

dev_dependencies:
  bloc_test: ^9.1.7
  test: ^1.25.8
  very_good_analysis: ^6.0.0
